name: auto_sign

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
    - cron: "30 5 * * 1"
    - cron: "0 0 * * 2"
    - cron: "55 1 * * 2"
    - cron: "30 5 * * 2"
    - cron: "50/1 1 * * 4"
    - cron: "40/1 2 * * 4"

jobs:
  run_sign:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip3 install requests
      - name: Run sign
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NAME: ${{ secrets.NAME }}
          ADDRESS: ${{ secrets.ADDRESS }}
          IMG: ${{ secrets.IMG }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LATITUDE: ${{ secrets.LATITUDE }}
        run: |
          python3 auto_sign.py
